on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify Git Repository 
        uses: actions/checkout@v2
      - name: Npm install
        run: npm install

      - name: Execute lint
        run: npx eslint .